// 球队名中文化映射 (英文/原文 → 中文)
// 合并自 backend matches.py EN_ZH_TEAM (271条) + 前端特色球队
// 找不到翻译时回退原文, 永不丢失数据

const TEAM_MAP: Record<string, string> = {

  // ── 世界杯/国家队 ──
  'Argentina': '阿根廷',
  'Australia': '澳大利亚',
  'Austria': '奥地利',
  'Belgium': '比利时',
  'Bolivia': '玻利维亚',
  'Brazil': '巴西',
  'Cameroon': '喀麦隆',
  'Canada': '加拿大',
  'Chile': '智利',
  'Colombia': '哥伦比亚',
  'Costa Rica': '哥斯达黎加',
  'Croatia': '克罗地亚',
  'Czech Republic': '捷克',
  'Denmark': '丹麦',
  'DR Congo': '民主刚果',
  'Ecuador': '厄瓜多尔',
  'Egypt': '埃及',
  'El Salvador': '萨尔瓦多',
  'England': '英格兰',
  'France': '法国',
  'Germany': '德国',
  'Ghana': '加纳',
  'Greece': '希腊',
  'Guinea': '几内亚',
  'Haiti': '海地',
  'Honduras': '洪都拉斯',
  'Hungary': '匈牙利',
  'Iran': '伊朗',
  'Italy': '意大利',
  'Ivory Coast': '科特迪瓦',
  'Jamaica': '牙买加',
  'Japan': '日本',
  'Mali': '马里',
  'Mexico': '墨西哥',
  'Morocco': '摩洛哥',
  'Netherlands': '荷兰',
  'New Zealand': '新西兰',
  'Nigeria': '尼日利亚',
  'Norway': '挪威',
  'Panama': '巴拿马',
  'Paraguay': '巴拉圭',
  'Peru': '秘鲁',
  'Poland': '波兰',
  'Portugal': '葡萄牙',
  'Qatar': '卡塔尔',
  'Republic of Ireland': '爱尔兰',
  'Romania': '罗马尼亚',
  'Russia': '俄罗斯',
  'Saudi Arabia': '沙特阿拉伯',
  'Scotland': '苏格兰',
  'Senegal': '塞内加尔',
  'Serbia': '塞尔维亚',
  'South Africa': '南非',
  'South Korea': '韩国',
  'Spain': '西班牙',
  'Sweden': '瑞典',
  'Switzerland': '瑞士',
  'Tunisia': '突尼斯',
  'Turkey': '土耳其',
  'Ukraine': '乌克兰',
  'United States': '美国',
  'Uruguay': '乌拉圭',
  'Venezuela': '委内瑞拉',
  'Wales': '威尔士',
  'Zimbabwe': '津巴布韦',
  'Curaçao': '库拉索',
  'Algeria': '阿尔及利亚',

  // ── 英超 ──
  'Arsenal': '阿森纳',
  'Arsenal FC': '阿森纳',
  'Aston Villa': '阿斯顿维拉',
  'AFC Bournemouth': '伯恩茅斯',
  'Bournemouth': '伯恩茅斯',
  'Brentford': '布伦特福德',
  'Brentford FC': '布伦特福德',
  'Brighton': '布莱顿',
  'Brighton & Hove Albion': '布莱顿',
  'Burnley': '伯恩利',
  'Burnley FC': '伯恩利',
  'Chelsea': '切尔西',
  'Chelsea FC': '切尔西',
  'Crystal Palace': '水晶宫',
  'Everton': '埃弗顿',
  'Everton FC': '埃弗顿',
  'Fulham': '富勒姆',
  'Fulham FC': '富勒姆',
  'Leeds': '利兹联',
  'Leeds United': '利兹联',
  'Leicester': '莱斯特城',
  'Leicester City': '莱斯特城',
  'Liverpool': '利物浦',
  'Liverpool FC': '利物浦',
  'Luton Town': '卢顿',
  'Manchester City': '曼城',
  'Manchester United': '曼联',
  'Newcastle': '纽卡斯尔',
  'Newcastle United': '纽卡斯尔',
  'Norwich City': '诺维奇',
  'Nottingham Forest': '诺丁汉森林',
  'Sheffield United': '谢菲尔德联',
  'Southampton': '南安普顿',
  'Southampton FC': '南安普顿',
  'Sunderland': '桑德兰',
  'Tottenham': '热刺',
  'Tottenham Hotspur': '热刺',
  'Watford': '沃特福德',
  'Watford FC': '沃特福德',
  'West Ham': '西汉姆',
  'West Ham United': '西汉姆',
  'Wolverhampton': '狼队',
  'Wolverhampton Wanderers': '狼队',

  // ── 西甲 ──
  'Barcelona': '巴塞罗那',
  'FC Barcelona': '巴塞罗那',
  'Real Madrid': '皇家马德里',
  'Atletico Madrid': '马德里竞技',
  'Atlético Madrid': '马德里竞技',
  'Sevilla': '塞维利亚',
  'Sevilla FC': '塞维利亚',
  'Real Sociedad': '皇家社会',
  'Real Betis': '皇家贝蒂斯',
  'Villarreal': '比利亚雷亚尔',
  'Villarreal CF': '比利亚雷亚尔',
  'Athletic Club': '毕尔巴鄂竞技',
  'Athletic Bilbao': '毕尔巴鄂竞技',
  'Valencia': '瓦伦西亚',
  'Valencia CF': '瓦伦西亚',
  'Celta de Vigo': '塞尔塔',
  'RC Celta': '塞尔塔',
  'CA Osasuna': '奥萨苏纳',
  'Getafe': '赫塔菲',
  'Getafe CF': '赫塔菲',
  'Rayo Vallecano': '巴列卡诺',
  'Mallorca': '马洛卡',
  'RCD Mallorca': '马洛卡',
  'Girona': '赫罗纳',
  'Girona FC': '赫罗纳',
  'UD Almería': '阿尔梅里亚',
  'UD Las Palmas': '拉斯帕尔马斯',
  'Cádiz CF': '加的斯',
  'Elche CF': '埃尔切',
  'Espanyol': '西班牙人',
  'RCD Espanyol': '西班牙人',
  'Deportivo': '拉科鲁尼亚',
  'Deportivo de La Coruña': '拉科鲁尼亚',
  'Levante UD': '莱万特',

  // ── 意甲 ──
  'Juventus': '尤文图斯',
  'AC Milan': 'AC米兰',
  'Milan': 'AC米兰',
  'Inter': '国际米兰',
  'Inter Milan': '国际米兰',
  'FC Internazionale Milano': '国际米兰',
  'Napoli': '那不勒斯',
  'SSC Napoli': '那不勒斯',
  'Roma': '罗马',
  'AS Roma': '罗马',
  'Lazio': '拉齐奥',
  'SS Lazio': '拉齐奥',
  'Atalanta': '亚特兰大',
  'Atalanta BC': '亚特兰大',
  'Fiorentina': '佛罗伦萨',
  'ACF Fiorentina': '佛罗伦萨',
  'Bologna': '博洛尼亚',
  'Bologna FC': '博洛尼亚',
  'Torino': '都灵',
  'Torino FC': '都灵',
  'Sassuolo': '萨索洛',
  'US Sassuolo': '萨索洛',
  'Empoli': '恩波利',
  'Empoli FC': '恩波利',
  'Cagliari': '卡利亚里',
  'Cagliari Calcio': '卡利亚里',
  'Udinese': '乌迪内斯',
  'Udinese Calcio': '乌迪内斯',
  'Hellas Verona': '维罗纳',
  'Genoa': '热那亚',
  'Genoa CFC': '热那亚',
  'US Cremonese': '克雷莫纳',
  'Lecce': '莱切',
  'US Lecce': '莱切',
  'Salernitana': '萨勒尼塔纳',
  'Spezia Calcio': '斯佩齐亚',
  'Sampdoria': '桑普多利亚',
  'Venezia FC': '威尼斯',
  'Palermo': '巴勒莫',

  // ── 德甲 ──
  'FC Bayern Munich': '拜仁慕尼黑',
  'FC Bayern München': '拜仁慕尼黑',
  'Bayern': '拜仁慕尼黑',
  'Borussia Dortmund': '多特蒙德',
  'Dortmund': '多特蒙德',
  'RB Leipzig': '莱比锡',
  'Bayer 04 Leverkusen': '勒沃库森',
  'Leverkusen': '勒沃库森',
  'VfB Stuttgart': '斯图加特',
  'Stuttgart': '斯图加特',
  'Eintracht Frankfurt': '法兰克福',
  'Frankfurt': '法兰克福',
  'SC Freiburg': '弗赖堡',
  'Freiburg': '弗赖堡',
  'TSG Hoffenheim': '霍芬海姆',
  'Hoffenheim': '霍芬海姆',
  'VfL Wolfsburg': '沃尔夫斯堡',
  'Wolfsburg': '沃尔夫斯堡',
  'Borussia Mönchengladbach': '门兴',
  'Mönchengladbach': '门兴',
  'FC Augsburg': '奥格斯堡',
  'Augsburg': '奥格斯堡',
  '1. FSV Mainz 05': '美因茨',
  'Mainz': '美因茨',
  '1. FC Union Berlin': '柏林联合',
  'Union Berlin': '柏林联合',
  'SV Werder Bremen': '不莱梅',
  'Werder Bremen': '不莱梅',
  'FC Schalke 04': '沙尔克04',
  'Schalke': '沙尔克04',
  'Hertha BSC': '柏林赫塔',
  'Hertha': '柏林赫塔',
  '1. FC Köln': '科隆',
  'FC Köln': '科隆',
  'Hamburger SV': '汉堡',
  'Hamburg': '汉堡',
  'VfL Bochum': '波鸿',
  'Bochum': '波鸿',
  '1. FC Heidenheim': '海登海姆',
  'Heidenheim': '海登海姆',
  'SV Darmstadt 98': '达姆施塔特',
  'Darmstadt': '达姆施塔特',
  'SC Paderborn': '帕德博恩',

  // ── 法甲 ──
  'Paris Saint-Germain': '巴黎圣日耳曼',
  'PSG': '巴黎圣日耳曼',
  'Marseille': '马赛',
  'Olympique de Marseille': '马赛',
  'Monaco': '摩纳哥',
  'AS Monaco': '摩纳哥',
  'Lyon': '里昂',
  'Olympique Lyonnais': '里昂',
  'Olympique Lyon': '里昂',
  'Lille': '里尔',
  'LOSC Lille': '里尔',
  'Rennes': '雷恩',
  'Stade Rennais FC': '雷恩',
  'Nice': '尼斯',
  'OGC Nice': '尼斯',
  'Lens': '朗斯',
  'RC Lens': '朗斯',
  'Nantes': '南特',
  'FC Nantes': '南特',
  'Montpellier': '蒙彼利埃',
  'Montpellier HSC': '蒙彼利埃',
  'Brest': '布雷斯特',
  'Stade Brestois 29': '布雷斯特',
  'Toulouse': '图卢兹',
  'Toulouse FC': '图卢兹',
  'Reims': '兰斯',
  'Stade de Reims': '兰斯',
  'Lorient': '洛里昂',
  'FC Lorient': '洛里昂',
  'Clermont': '克莱蒙',
  'Clermont Foot 63': '克莱蒙',
  'Le Havre': '勒阿弗尔',
  'Le Havre AC': '勒阿弗尔',
  'Metz': '梅斯',
  'FC Metz': '梅斯',
  'Angers': '昂热',
  'Angers SCO': '昂热',
  'Troyes': '特鲁瓦',
  'ESTAC Troyes': '特鲁瓦',
  'Auxerre': '欧塞尔',
  'AJ Auxerre': '欧塞尔',
  'SC Bastia': '巴斯蒂亚',
  'Saint-Étienne': '圣埃蒂安',
  'AS Saint-Étienne': '圣埃蒂安',
  'SM Caen': '卡昂',

  // ── 中超 ──
  'Zhejiang': '浙江队',
  'Qingdao Hainiu FC': '青岛海牛',
  'Shanghai Shenhua': '上海申花',
  'Shanghai Port': '上海海港',
  'Beijing Guoan': '北京国安',
  'Wuhan Three Towns': '武汉三镇',
  'Shandong Taishan': '山东泰山',
  'Chengdu Rongcheng': '成都蓉城',
  'Tianjin Jinmen Tiger': '天津津门虎',
  'Dalian Pro': '大连人',
  'Cangzhou Mighty Lions': '沧州雄狮',
  'Henan': '河南队',
  'Meizhou Hakka': '梅州客家',
  'Nantong Zhiyun': '南通支云',

  // ── 瑞典超 ──
  'Djurgardens IF': '尤尔加登',
  'Halmstads BK': '哈尔姆斯塔德',
  'Malmö FF': '马尔默',
  'AIK': 'AIK索尔纳',
  'IF Elfsborg': '埃尔夫斯堡',
  'BK Häcken': '哈肯',
  'IFK Göteborg': '哥德堡',
  'Hammarby IF': '哈马比',

  // ── 巴甲 ──
  'Palmeiras': '帕尔梅拉斯',
  'Corinthians': '科林蒂安',
  'Flamengo': '弗拉门戈',
  'Fluminense': '弗鲁米嫩塞',
  'São Paulo': '圣保罗',
  'Santos': '桑托斯',
  'Atlético Mineiro': '米内罗竞技',
  'Athletico Paranaense': '巴拉那竞技',
  'Internacional': '巴西国际',
  'Grêmio': '格雷米奥',
  'Botafogo': '博塔弗戈',
  'Bahia': '巴伊亚',
  'Fortaleza': '福塔莱萨',
  'Cruzeiro': '克鲁塞罗',
  'Vasco da Gama': '瓦斯科·达伽马',
  'Sport Recife': '累西腓体育',
  'América Mineiro': '米内罗美洲',
  'Ceará': '塞阿拉',
  'Athletic Club (MG)': '米内罗体育',

  // ── 阿甲/南美 ──
  'Boca Juniors': '博卡青年',
  'River Plate': '河床',
  'Racing Club': '竞赛俱乐部',
  'Independiente': '独立竞技',
  'San Lorenzo': '圣洛伦索',
  'Peñarol': '佩纳罗尔',
  'Nacional': '民族队',

  // ── MLS ──
  'Inter Miami': '迈阿密国际',
  'LA Galaxy': '洛杉矶银河',
  'LAFC': '洛杉矶FC',
  'New York City FC': '纽约城',
  'Atlanta United': '亚特兰大联',

  // ── 荷甲/其他 ──
  'Ajax': '阿贾克斯',
  'PSV': '埃因霍温',

  // ── 其他 ──
  'Atlético Paranaense': '巴拉那竞技',
  'Londrina': '隆德里纳',
}

/**
 * 球队名: 原样返回 token 字符, 不做任何翻译/改写.
 *
 * 2026-08-24 用户铁律: "token 返回什么字符, 就映射什么名称".
 * GQ token 已直接返回中文队名(如 奥林匹克FC / 烈焰骑士FC), 任何二次翻译
 * 表(TEAM_MAP)都会引入错配/幻觉(如把 obscure 联赛队名译成不存在的队).
 * 故 localizeTeam 改为透传, 永不改写. TEAM_MAP 保留仅供人工参考, 不再参与渲染.
 */
export function localizeTeam(name: string | undefined | null): string {
  // 仅做空值/空白兜底, 其余原样返回 token 字符
  if (!name) return ''
  return name.trim()
}

/** 反向查找: 中文 -> 英文. 翻译表已停用, 返回 undefined (调用方须自行兜底原文). */
export function toEnglishName(zh: string): string | undefined {
  return undefined
}
